# Give your application a name
server.port=8081
spring.application.name=finance

# Enable H2 Database Console so you can see your data in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database connection settings
spring.datasource.url=jdbc:h2:file:/opt/render/project/src/data/financedb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# This command creates database tables automatically based on your Java code
spring.jpa.hibernate.ddl-auto=update

# Print SQL queries to the IntelliJ console for easy grading/debugging
spring.jpa.show-sql=true